### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by ld9866** [israfelsr/lfmm-python#1]
Hello!
When I followed your example, I found that there was no such file in my directory. I would like to ask you what is the reason for this? Where do I go to find this file requirements.txt?
good day!

#
pip install -r requirements.txt

**Comment by israfelsr** [comment]
Hi! 
Oh I'm sorry, I forgot to create it. I added now to the main folder. 
Try pulling again and it should be ok.

Good day to you too!
